schema: 
  - ./graphql.schema.json
documents:
  - ./*.graphql
extensions:
  codegen:
    generates:
      ./src/generated/graphql.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-apollo-angular